config/routes.rb
Rails.application.routes.draw do
  root 'users#matches'

  resources :passwords,
    controller: 'clearance/passwords',
    only: [:create, :new]

  resource :session,
    controller: 'clearance/sessions',
    only: [:create]

  resources :users,
    controller: 'users',
    only: Clearance.configuration.user_actions do
      resource :password,
        controller: 'clearance/passwords',
        only: [:create, :edit, :update]
    end

  resources :origins, only: [:create, :new]
  resources :destinations, only: [:create, :new]
  resources :users, only: [:show, :edit, :update]

  get 'users/:id/matches', to: 'users#matches'
  get 'users/:id/deactivate', to: 'users#deactivate', as: 'deactivate'
  get 'users/:id/activate', to: 'users#activate', as: 'activate'

  get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
  delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'

  get '/help', to: 'pages#help'
  get '/tos', to: 'pages#tos'

  if Clearance.configuration.allow_sign_up?
    get '/sign_up' => 'users#new', as: 'sign_up'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
  belongs_to :origin
  belongs_to :destination
  accepts_nested_attributes_for :origin
  accepts_nested_attributes_for :destination

  EMAIL_REGEX = /\A.+@(scarletmail.)?rutgers\.edu\z/i

  validates_presence_of :first_name, :last_name, :gender, :role
  validates :email, presence: true, uniqueness: true, format:{ with: EMAIL_REGEX }
  GENDERS = %w[male female]


  def matches
    @matches = nil
    return if self.deactivated?
    #find users that live where i want to live
    #we have to pick all origins with this specific building and campus
    #this is because there are "duplicate" entries, because floor and room type makes the "same" locations "different"
    if self.destination.campus == "anywhere"
      @where_i_want_to_live = Origin.all
    elsif self.destination.building == "anywhere"
      @where_i_want_to_live = Origin.where(campus: self.destination.campus)
    else
      @where_i_want_to_live = Origin.where(campus: self.destination.campus, building: self.destination.building)
    end
    return if @where_i_want_to_live.nil?
    @residents = []
    @where_i_want_to_live.each do |loc|
      @residents = @residents + User.where(origin_id: loc.id)
    end
    #find users that want to live where i live
    @where_i_live = Destination.where(campus: self.origin.campus, building: self.origin.building)
    #also include any users that want to live on my campus, but "anywhere", which is stored as an explicit row
    @where_i_live = @where_i_live + Destination.where(campus: self.origin.campus, building: "anywhere")
    #also include any users that want to live anywhere
    @where_i_live = @where_i_live + Destination.where(campus: "anywhere")
    return if @where_i_live.nil?
    @migrators = []
    @where_i_live.each do |loc|
      @migrators = @migrators + User.where(destination_id: loc.id)
    end
    #the intersection of these two arrays are our matches
    @matches = @residents & @migrators
    #only pick users of the same gender
    @matches = @matches.select do |match|
      match.gender == self.gender
    end
    @matches = @matches.select do |match|
      match.role != "deactivated"
    end
    #make sure you don't match with yourself
    @matches = @matches.select do |match|
      match.email != self.email
    end

  end

  def full_name
    self.first_name + " " + self.last_name
  end

  def full_name_last_initial
    self.first_name + " " + self.last_name.chars.first + "."
  end

  def origin_building_campus
    self.origin.building.titleize + ", " + self.origin.campus.titleize
  end

  def destination_building_campus
    if self.destination.campus == "anywhere"
      @location = "Anywhere"
    elsif self.destination.building == "anywhere"
      @location = self.destination.campus.titleize
    else
      @location = self.destination.building.titleize + ", " + self.destination.campus.titleize
    end
  end

  def origin_summary
    "Floor " + self.origin.floor.to_s + ", " + self.origin.building.titleize + ", " + self.origin.campus.titleize
  end

  def destination_summary
    destination_building_campus
  end

  def description
    "Lives in floor " + self.origin.floor.to_s + " of " + self.origin_building_campus + " and wants to move to " + self.destination_building_campus
  end

  def deactivated?
    self.role == "deactivated"
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  before_action :require_login, except: [:new, :create]
  load_and_authorize_resource
  skip_load_resource :only => :create


  def matches
    @matches = current_user.matches
  end

  def new
    @user = User.new
    @origin = Origin.new
    @destination = Destination.new

    @user.origin = @origin
    @user.destination = @destination

    render template: "users/new"
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    @origin = Origin.find_or_create_by(campus: params[:user][:origin_attributes][:campus],
                                      building: params[:user][:origin_attributes][:building],
                                      floor: params[:user][:origin_attributes][:floor],
                                      style: params[:user][:origin_attributes][:style])
    @destination = Destination.find_or_create_by(campus: params[:user][:destination_attributes][:campus],
                                                building: params[:user][:destination_attributes][:building])

    @user.origin = @origin
    @user.destination = @destination

    if @user.save
      redirect_to @user
      flash[:success] = "User was successfully updated!"
    else
      flash.now[:error] = "User was not successfully updated."
      render :edit
    end
  end

  def create
    @user = user_from_params

    @user.origin = Origin.find_or_create_by(campus: @user.origin.campus, building: @user.origin.building, floor: @user.origin.floor, style: @user.origin.style)
    @user.destination = Destination.find_or_create_by(campus: @user.destination.campus, building: @user.destination.building)

    @user.role = "student"
    if @user.save
      sign_in @user
      redirect_back_or url_after_create
    else
      render template: "users/new"
    end
  end

  def deactivate
    @user = User.find(params[:id])
    if @user.update_attribute(:role, "deactivated")
    else
      flash[:error] = "Your account could not be deactivated"
      redirect_to user_path(@user)
    end
  end

  def activate
    @user = User.find(params[:id])
    if @user.update_attribute(:role, "student")
      redirect_to user_path(@user)
      flash[:success] = "Your account was reactivated! Please update your information"
    else
      flash[:error] = "Your account could not be reactivated"
      redirect_to user_path(@user)
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :first_name, :last_name, :gender, :note,
      destination_attributes: [:campus, :building], origin_attributes: [:campus, :building, :floor, :style])
  end
end

app/views/users/_change_location.html.haml
= bootstrap_form_for(@user, label_errors: true) do |form|
  %h3 Where do you currently live?

  = form.fields_for :origin do |origin|
    = origin.collection_select :campus, Location::CAMPUSES, :to_s, :titleize
    = origin.collection_select :building, Location::BUILDINGS_LIVINGSTON, :to_s, :titleize
    = origin.number_field :floor, value: :empty
    = origin.collection_select :style, Location::STYLES, :to_s, :to_s

  = form.text_field :note, label: "Additional information about your living situation"

  %h3 Where do you want to live?

  = form.fields_for :destination do |destination|
    = destination.collection_select :campus, Location::CAMPUSES_A, :to_s, :titleize, hide_label: true
    = destination.collection_select :building, Location::BUILDINGS_LIVINGSTON, :to_s, :titleize, hide_label: true

  = form.submit

  = javascript_tag "var BUILDINGS_LIVINGSTON = #{Location::BUILDINGS_LIVINGSTON};"
  = javascript_tag "var BUILDINGS_BUSCH = #{Location::BUILDINGS_BUSCH};"
  = javascript_tag "var BUILDINGS_COLLEGE_AVENUE = #{Location::BUILDINGS_COLLEGE_AVENUE};"
  = javascript_tag "var BUILDINGS_COOK_DOUGLASS = #{Location::BUILDINGS_COOK_DOUGLASS};"

  = javascript_include_tag 'location'

app/views/users/_form.html.haml
= bootstrap_form_for(@user, label_errors: true) do |form|
  %h3 Your information
  %h6 Email must end in @rutgers.edu or @scarletmail.rutgers.edu
  %h6 Your email will be displayed to other users
  = form.text_field :email, type: 'email', placeholder: "Email", hide_label: true
  = form.password_field :password, placeholder: "Password", hide_label: true

  = form.text_field :first_name, placeholder: "First name", hide_label: true

  %h6 Only the first initial of your last name will be displayed to other users
  = form.text_field :last_name, placeholder: "Last name", hide_label: true

  = form.collection_select :gender, User::GENDERS, :to_s, :humanize

  %br

  %h3 Where do you currently live?

  = form.fields_for :origin do |origin|
    = origin.collection_select :campus, Location::CAMPUSES, :to_s, :titleize
    = origin.collection_select :building, Location::BUILDINGS_LIVINGSTON, :to_s, :titleize
    = origin.number_field :floor
    = origin.collection_select :style, Location::STYLES, :to_s, :to_s
  = form.label "Additional information about your living situation (optional)"
  %h6
    Here you can include information like the learning community you're a part of,
    if you live in special interest housing, or any other housing restrictions
  = form.text_field :note, hide_label: true

  %br

  %h3 Where do you want to live?

  = form.fields_for :destination do |destination|
    = destination.collection_select :campus, Location::CAMPUSES_A, :to_s, :titleize, hide_label: true
    = destination.collection_select :building, Location::BUILDINGS_LIVINGSTON, :to_s, :titleize, hide_label: true
  %h5
    By signing up you agree with Swap Sniper's
    = link_to "Terms of Services", tos_path
  = form.submit

  = javascript_tag "var BUILDINGS_LIVINGSTON = #{Location::BUILDINGS_LIVINGSTON};"
  = javascript_tag "var BUILDINGS_BUSCH = #{Location::BUILDINGS_BUSCH};"
  = javascript_tag "var BUILDINGS_COLLEGE_AVENUE = #{Location::BUILDINGS_COLLEGE_AVENUE};"
  = javascript_tag "var BUILDINGS_COOK_DOUGLASS = #{Location::BUILDINGS_COOK_DOUGLASS};"

  = javascript_include_tag 'location'

app/views/users/_match.html.haml
%li.list-group-item
  %h4
    = match.full_name_last_initial
  %p
    Lives in:
    %strong
      = match.origin_summary
  %p
    Room type:
    %strong
      = match.origin.style
  %p
    Wants to live in:
    %strong
      = match.destination_summary
  -unless match.note.try(:empty?)
    %p
      Additional information:
      = match.note
  %p
    .accordion{id: "accordion#{match.id}"}
      .accordion-group
        .accordion-heading
          .accordion-toggle{"data-toggle" => "collapse", "data-parent"=>"#accordion#{match.id}", href: "#collapse#{match.id}"}
            = link_to "Click here to see their email"
        .accordion-body.collapse{id: "collapse#{match.id}"}
          .accordion-inner
            Contact them at
            = mail_to match.email, match.email
            to see if they want to swap!

app/views/users/edit.html.haml
%h3.text-center Updating your location
.col-md-4.col-md-offset-4
  = render 'change_location'

app/views/users/matches.html.haml
- if @matches.nil? or @matches.empty?
  .text-center
    %h2
      No matches :(
    %h4
      Be sure to check back soon
- else
  .text-center
    %h2 Your matches
    %h4
      You are trying to swap to:
      = current_user.destination_summary
  - @matches.each do |match|
    %ul.list-group.col-md-8.col-md-offset-2
      = render partial: 'users/match', :locals => {:match => match}

app/views/users/new.html.haml
.col-md-4.col-md-offset-4
  %h1.text-center
    Sign up
.row
  .col-md-4.col-md-offset-4
    =render '/users/form'
    .other-links
      = link_to t(".sign_in"), sign_in_path

app/views/users/show.html.haml
- if @user.deactivated?
  .col-md-10.col-md-offset-1.text-center
    %h3.alert.alert-danger
      Your account is deactivated! Please click
      = link_to "here", activate_path(@user)
      to reactivate it
.col-md-6.col-md-offset-3.text-center
  %h2 My Profile
  %ul.list-group
    %li.list-group-item
      %h2.list-group-item-heading
        = @user.full_name
      %h4.list-group-item-text
        = @user.email
    %li.list-group-item
      %h3.list-group-item-heading
        Lives in:
      %h4.list-group-item-text
        = @user.origin_summary
      %h5.list-group-item-text
        = @user.origin.style
    %li.list-group-item
      %h3.list-group-item-heading
        Wants to live in:
      %h4.list-group-item-text
        = @user.destination_summary
    - unless @user.note.try(:empty?)
      %li.list-group-item
        %h4.list-group-item-heading
          Additional information about your living situation:
        %h5.list-group-item-text
        = @user.note


  %h5
    = link_to edit_user_path(@user) do
      Update my location information
  - unless @user.deactivated?
    %h5
      = link_to deactivate_path(@user), data: { confirm: "Are you sure you want to deactivate your account? Users won't be able to match with you until you reactivate." } do
        Deactivate my account