config/routes.rb
Rails.application.routes.draw do
  root 'users#matches'

  resources :passwords,
    controller: 'clearance/passwords',
    only: [:create, :new]

  resource :session,
    controller: 'clearance/sessions',
    only: [:create]

  resources :users,
    controller: 'users',
    only: Clearance.configuration.user_actions do
      resource :password,
        controller: 'clearance/passwords',
        only: [:create, :edit, :update]
    end

  resources :origins, only: [:create, :new]
  resources :destinations, only: [:create, :new]
  resources :users, only: [:show, :edit, :update]

  get 'users/:id/matches', to: 'users#matches'
  get 'users/:id/deactivate', to: 'users#deactivate', as: 'deactivate'
  get 'users/:id/activate', to: 'users#activate', as: 'activate'

  get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
  delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'

  get '/help', to: 'pages#help'
  get '/tos', to: 'pages#tos'

  if Clearance.configuration.allow_sign_up?
    get '/sign_up' => 'users#new', as: 'sign_up'
  end
end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default{role:"navigation"}
  .navbar-header
    %button.navbar-toggle{type:"button", "data-target"=>"#navbarCollapse", "data-toggle"=>"collapse"}
      %span.sr-only
        Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand{href:"/"}
      Swap Sniper
  -if signed_in?
    #navbarCollapse.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to user_path(current_user) do
            = current_user.full_name
        %li
          = link_to "/users/#{current_user.id}/matches" do
            .badge
              = current_user.matches ? current_user.matches.count : 0
            matches
        %li
          = link_to "Help", help_path
        %li
          = link_to sign_out_path, method: "delete" do
            Sign Out
  -else
    #navbarCollapse.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to "Help", help_path
        %li
          = link_to sign_in_path do
            Sign In
        - if Clearance.configuration.allow_sign_up?
          %li
            = link_to t(".sign_up"), sign_up_path
#error_explanation.center
  - flash.each do |name, msg|
    - case name
    - when "error"
      .alert.alert-danger.text-center
        = content_tag :div, msg, class: name
    - when "success"
      .alert.alert-success.text-center
        = content_tag :div, msg, class: name

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      Swap Sniper
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    = yield
    = render 'layouts/footer'